const ACCOUNT_DATA = [
  {
    type: "demo",
    title: "Demo Account",
    min: "Free",
    spreads: "Variable",
    commission: "None",
    desc: "Perfect for beginners to practice trading with virtual funds in real market conditions without any risk.",
  },
  {
    type: "standard",
    title: "Standard Account",
    min: "$100+",
    spreads: "Normal",
    commission: "Low",
    desc: "Balanced account type with normal spreads and low commissions, designed for intermediate traders.",
  },
  {
    type: "micro",
    title: "Mini / Micro / Cent Account",
    min: "$10+",
    spreads: "Slightly Higher",
    commission: "Low",
    desc: "Trade with small capital using slightly higher spreads. Ideal for testing strategies at a lower risk.",
  },
  {
    type: "ecn",
    title: "ECN Account",
    min: "$200+",
    spreads: "Ultra-Low",
    commission: "Yes",
    desc: "Enjoy ultra-low spreads with direct market access. Best for professional traders who need speed and precision.",
  },
  {
    type: "stp",
    title: "STP Account",
    min: "$100+",
    spreads: "Moderate",
    commission: "Low",
    desc: "Straight-through processing with moderate spreads and fast execution, tailored for active traders.",
  },
  {
    type: "islamic",
    title: "Islamic (Swap-Free) Account",
    min: "Varies",
    spreads: "Normal",
    commission: "Fixed Fee",
    desc: "Swap-free trading with fixed fees, specifically designed for Muslim traders who follow Shariah principles.",
  },
  {
    type: "vip",
    title: "VIP / Premium Account",
    min: "$10,000+",
    spreads: "Tightest",
    commission: "Performance-Based",
    desc: "Exclusive account with the tightest spreads and performance-based commissions for high-volume traders.",
  },
  {
    type: "managed",
    title: "Managed (PAMM) Account",
    min: "$500+",
    spreads: "Varies",
    commission: "Performance-Based",
    desc: "Investors can allocate funds to professional managers. Spreads and fees vary with performance.",
  },
];
