 const posts = [
    { title: "Technical Analysis: EUR/USD Outlook", img: "https://images.unsplash.com/photo-1569025690938-a00729c9e2e9?auto=format&fit=crop&w=1600&q=80", desc: "EUR/USD is testing resistance zones. See what patterns traders are watching this week.", tag: "Technical Analysis", author: "Mark T." },
    { title: "Weekly Market Recap", img: "https://images.unsplash.com/photo-1561414927-6d86591d0c4f?auto=format&fit=crop&w=1600&q=80", desc: "Catch up on how major forex pairs, gold, and indices performed in the past week.", tag: "Market Recap", author: "Sarah K." },
    { title: "PayKuber FX Updates", img: "https://images.unsplash.com/photo-1605902711622-cfb43c4437d2?auto=format&fit=crop&w=1600&q=80", desc: "We’re launching smart alerts and advanced charting tools for pro-level trading.", tag: "Company News", author: "Team PayKuber" },
    { title: "Guest Insights: Risk Management", img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1600&q=80", desc: "Pro trader John Davis shares his golden rules for surviving volatile forex markets.", tag: "Guest Trader", author: "John Davis" },
    { title: "Top 5 Mistakes Beginners Make", img: "https://images.unsplash.com/photo-1581091226825-10f0c9b7bf97?auto=format&fit=crop&w=1600&q=80", desc: "Avoid the most common pitfalls and accelerate your learning curve as a trader.", tag: "Education", author: "Emily R." },
    { title: "The Rise of AI in Forex", img: "https://images.unsplash.com/photo-1600267185393-e1588df7b331?auto=format&fit=crop&w=1600&q=80", desc: "Artificial Intelligence is changing trading strategies. Here's how to adapt.", tag: "Innovation", author: "Alex N." },
    { title: "Gold Outlook 2025", img: "https://images.unsplash.com/photo-1590490360181-d7e37c95f1b2?auto=format&fit=crop&w=1600&q=80", desc: "As inflation rises, traders turn to gold. Here’s the technical and fundamental view.", tag: "Commodities", author: "Lisa M." },
    { title: "Psychology of Trading", img: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1600&q=80", desc: "Master your emotions to master the markets. Learn practical psychology tips.", tag: "Mindset", author: "David G." },
    { title: "Crypto & Forex Correlation", img: "https://images.unsplash.com/photo-1621507419387-56f33923995f?auto=format&fit=crop&w=1600&q=80", desc: "Discover how crypto volatility impacts forex pairs and how to hedge smartly.", tag: "Crypto", author: "Sophia B." },
    { title: "Scalping Strategies 2025", img: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1600&q=80", desc: "High-speed trading techniques that thrive in volatile conditions.", tag: "Strategy", author: "Chris P." },
  ];

  export default posts;